### ISSUE TITLE
Return a custom value

### ISSUE THREAD

**Issue by tage64** [alecmocatta/replace_with#8]
Hello,

Would it be possible to make some more functions which makes it possible to return a value.
In the abort case it may look like this:

`pub fn replace_with_or_abort<T, U, F>(dest: &mut T, f: F) -> U
    where F: FnOnce(T) -> (T, U)`

I can make a pr if you want.

Tage

**Comment by alecmocatta** [comment]
Thanks for the issue Tage,

Returning a value from the closure passed to `replace_with_or_abort` can be achieved like:

```rust
let mut ret = None;
replace_with_or_abort(&mut a, |old_value| {
    ...
    ret = Some(...);
    new_value
});
let ret = ret.unwrap();
```

If it's a common pattern then the extra `ret` variable could get annoying. I'm wondering what your use case is, if the above is sufficient for it, and if not how common this pattern is for you?

**Comment by tage64** [comment]
> I'm wondering what your use case is, if the above is sufficient for it, and if not how common this pattern is for you?

The pattern may not be very common, but it is very handy when it is needed. In my case I have a mutable reference to a type which implements a trait with conversion methods to another type and back to the original type again. The conversion methods take the original type by value. I want to retrieve a value from the other type. This might be better shown by an example.

```
fn f<T, U>(t: &mut T) -> _
    where T: Into<U> + From<U>,
{
    let res = Option::new();
    replace_with_or_abort(t, |t| {
        let u = t.into();
        res = Some(u.get_some_value());
        T::from(u)
    });
    res.unwrap()
}
```

The above code could effectively be written like this instead:

```
fn f<T, U>(t: &mut T) -> _
    where T: Into<U> + From<U>,
{
    replace_with_or_abort_and_return(t, |t| {
        let u = t.into();
        (u.get_some_value(), T::from(u))
    })
}
```

While using an Option like in the first example works, it doesn't feel most correct and it introduces a small performance overhead.

We may how ever need to come up with a better and shorter name.

**Comment by alecmocatta** [comment]
Sorry for the delay, I went away and overlooked this on my return.

Thanks for the explanation, I see better now the motivation. I saw your fork earlier and I'd be happy to take a look at a PR.

Any suggestions for a good shorter name I'm all ears!
